### PR TITLE
Update shell_elvish.go to the newer (non-deprecated) Elvish syntax

### PR DESCRIPTION
**Pull request by icidasset**
Upgrades the Elvish hook to the newer Elvish syntax:
https://elv.sh/blog/0.17.0-release-notes.html
https://github.com/elves/upgrade-scripts-for-0.17#elvish-script-upgrader-for-017

### CODE REVIEW

**Review by mmlb — COMMENTED** [review]
@zimbatm this lgtm as an elvish user.

**Comment by zimbatm** [comment]
@icidasset do you mind rebasing? I'm not sure why the CI didn't run.

**Comment by icidasset** [comment]
> @icidasset do you mind rebasing? I'm not sure why the CI didn't run.

Done 👀

**Comment by zimbatm** [comment]
thanks!

**Comment by avioli** [comment]
Since 0.18.0 - syntax should be `try {} catch e {}`, not `try {} except e {}`, since `except` is [now deprecated and will be removed from 0.19.0](https://elv.sh/blog/0.18.0-release-notes.html#deprecated-features)

**Pull request merged**
