### PR TITLE
Issue #303- check if dir is a symlink

### PR DESCRIPTION
**Pull request by etcusrvar**
https://github.com/direnv/direnv/issues/303

Enabled and fixed the test case that was added and commented out 5 years ago.

Tested on Linux and macOS. (I ran the .sh test script, and made the same changes to the .tcsh script but didn't run it.)

### CODE REVIEW

**Comment by zimbatm** [comment]
thanks! I am glad that you took the time fixing this issue.

Do you know if it would work if the parent folder was a symlink too? I am sure that your patch fixes the common case but am suspecting that it wouldn't work with deeper symlink structures.

**Comment by etcusrvar** [comment]
You are correct-- I verified that this fix as is will only work if `$(pwd)` itself is a symlink. It won't work if there is a symlink somewhere down the path. For that to work, there would have to be something like a `realpath` or `readlink -f` check. Something like this:

      if [[ "$(pwd)" != "$(readlink -f "$(pwd)")" ]]; then
        rcpath="$(cd "$(dirname "$(pwd)/$rcpath")" && pwd)"
      fi

I have this working locally on both Linux and macOS and can add to this PR if you think that using `realpath` or `readlink` is an acceptable solution. There are compatibility/portability issues with using either of these commands, and I don't know how important that is to the project.

**Comment by zimbatm** [comment]
direnv has the internal expand_path command for cross-platform purposes.

In regards to the symlink, I don't think that we should ever resolve them. The goal of the symlinks is to teleport some of the filesystem onto another part of the tree. When resolving the symlinks it's not respecting that.

**Comment by hexmode** [comment]
What needs to happen to get this merged? I'm running into this problem.

**Comment by blalor** [comment]
Just ran into this, as well; would love to see it merged!

**Comment by zimbatm** [comment]
I would love to get this fixed as well but fear that it's opening a rabbit hole. There are many ways that folders can be symlinked together. This is fixing one scenario and I don't see a solution that solves all the potential combinations.

**Comment by zimbatm** [comment]
It's mainly of my own doing, direnv doesn't have enough code coverage that I am able to merge changes with confidence. Since I am the one answering to all issues and also fixing most of the bugs, I can already see how this change will have ripple effects. I am not looking forward to debug the user's convoluted symlink setups ^_^

**Comment by hexmode** [comment]
>... direnv doesn't have enough code coverage that I am able to merge changes with confidence.

Would it be fair to say, then, that improving code coverage is a prerequisite for this?  I just opened #409 for that.

**Comment by zimbatm** [comment]
thanks @hexmode. I really appreciate every contributions but have limited time. It would be nice to have a second core contributor joining the projects but power law distribution and all.

**Comment by etcusrvar** [comment]
stale

**Pull request closed without merging**
