### PR TITLE
Add a TOML configuration file, support whitelisting envrc's regardless of their content's hash

### PR DESCRIPTION
**Pull request by anp**
With this PR, direnv now supports a configuration file at `CONFIG_DIR/config.toml`, and adds support for a `whitelist` key. Any `.envrc` files which match the patterns are allowed, regardless of whether the specific path & contents of the envrc file have been explicitly `allow`ed.

Here's an example TOML file:

```toml
[whitelist]
prefix = ["/Users/adam/code/foo"]
exact = [
    "/Users/adam/code/bar",
    "/Users/adam/code/quux/.envrc"
]
```

In this example, any envrc underneath the `foo` directory (including subdirectories) is trusted, even if its contents have changed. The topmost envrc in the `quux` directory is trusted as well, but not those of subdirectories.

Addresses https://github.com/direnv/direnv/issues/180
Supersedes https://github.com/direnv/direnv/pull/328

### CODE REVIEW

**Comment by anp** [comment]
I'll take a look at these failing tests soon.

**Comment by zimbatm** [comment]
It looks like it's failing the test if the config.toml is missing. It should just ignore that step if it's the case.

**Comment by anp** [comment]
Agreed! There's one edge case that I think it should handle, which is warning the user (over stderr?) if the config file exists but can't be parsed. Going to add that now, let me know if you'd like to handle that case differently.

**Comment by zimbatm** [comment]
yes good thinking!

**Comment by anp** [comment]
Updated, my original intent was to not error in this circumstance, but my unfamiliarity with Go meant I was accidentally assigning a value to the `err` value for the whole functions! Fixed and tests are passing for me locally. Will wait for CI.

**Pull request merged**
