### PR TITLE
`direnv status --json`

### PR DESCRIPTION
**Pull request by shivaraj-bh**
Was mentioned twice:
- https://github.com/direnv/direnv/issues/244#issuecomment-520487528
- https://github.com/direnv/direnv/issues/520#issuecomment-532892797

It will be used here:
https://github.com/srid/nix-health/issues/4

I have very little exposure working with GO, please correct me if I am wrong anywhere.

### CODE REVIEW

**Comment by zimbatm** [comment]
hey, thanks for the contrib!

The change looks reasonable overall. The only thing that needs to be looked into is why the loadedRC is not marked as allowed, even though it was just loaded:

```
{
  "config": {
    "ConfigDir": "/home/zimbatm/.config/direnv",
    "SelfPath": "/home/zimbatm/go/src/github.com/direnv/direnv/direnv"
  },
  "state": {
    "foundRC": {
      "allowed": true,
      "path": "/home/zimbatm/go/src/github.com/direnv/direnv/.envrc"
    },
    "loadedRC": {
      "allowed": false,
      "path": "/home/zimbatm/go/src/github.com/direnv/direnv/.envrc"
    }
  }
}

```

**Comment by shivaraj-bh** [comment]
> The change looks reasonable overall. The only thing that needs to be looked into is why the loadedRC is not marked as allowed, even though it was just loaded

I am guessing that's because `LoadedRC()` calls `RCFromEnv` that returns a `RC` struct with empty `allowPath` and the only other way `Allowed()` will be true is if `direnv.toml` whitelists a path or prefix. 
https://github.com/direnv/direnv/blob/cece664987549dade37a4314feaf7084190a6685/internal/cmd/rc.go#L89-L117 

Is this a bug?

**Comment by shivaraj-bh** [comment]
@zimbatm I have raised a [PR](https://github.com/direnv/direnv/pull/1157) to fix this, let me know if my understanding here is right.

**Comment by srid** [comment]
I would love to see this get merged and included in next release.

**Comment by thenbe** [comment]
I was about to open an issue about the output of `direnv status --json` being unintuitive. But when I find this thread, I started suspecting that I am misunderstanding the output.




Does the output seem confusing to you guys? Or am I misunderstanding it?

For context, all I'm trying to detect is whether direnv has already been set or if `direnv allow` needs to be called. From this output, I can conclude that `direnv allow` has already been set if `allowed = 0`, which is what I meant by "unintuitive" earlier.

**Comment by shivaraj-bh** [comment]
@thenbe You are right, it does seem unintuitive. 

The reason why you see integers now instead of bool (which was the case when the PR was merged), is due to this [PR](https://github.com/direnv/direnv/pull/1158). To be specific, these specific lines from `internal/cmd/rc.go`: 
```go
type AllowStatus int
const (
	Allowed AllowStatus = iota
	NotAllowed
	Denied
)
```
Due to the use of `iota` the states get assigned 0, 1, 2 in the order that they are written above. That justifies the output you see.

FWIW, I think it could very well be an issue to improve the readability of the output, feel free to create one.

**Comment by thenbe** [comment]
Oh, this makes sense now that I realize the number represents a status code and not a counter of some sort.

As for improving readability, I've opened a separate ticket here #1211 with one suggestion for how we can do so.

**Pull request merged**
