### PR TITLE
Added some documentation on how to set up the hook

### PR DESCRIPTION
**Pull request by danielmbarlow**
Please check that understand properly. Thanks.

### CODE REVIEW

**Comment by zimbatm** [comment]
Hi @danielmbarlow, thanks for your contribution. I have left a few comments on the changeset, hope I don't come off as defensive. How is your direnv experience so far ? I'm interested in getting general feedback too.

Cheers,
zimbatm

**Comment by pwaller** [comment]
Yeah, profile loading is a bit of a mess and I've seen little in the way of clear guidance for newbies on the matter.

My preference is to put things like direnv or path modifications in my `.profile` (which bash will read) and then enable `run command as login shell` in my terminals.

image

`.bashrc` is run whenever bash starts interactively, including if you happen to invoke bash from bash (which you might do via tmux or screen), it will re-do the environment modifications even though they are already present. Whilst not necessarily harmful to re-do environment modifications, I've seen this lead to some confusion (and for example cause it to destroy `.bash_history` unders some configuraitons).

**Comment by pwaller** [comment]
In fact, I have one thing in my `.bashrc`, and it's `shopt -s histappend`, which prevents the history from being destroyed. In my `.profile` I also have `export HISTFILE=~/.my_bash_history` which means if a bash instance starts up which doesn't have `histappend` set, it won't have `HISTFILE` set either and so it can't possibly destroy `~/.my_bash_history`.

**Comment by zimbatm** [comment]
That's why direnv is best configured in the `.bashrc`, it is only needed for interactive bash sessions. The bash extension mechanism happen to depend on an environment variable (PROMPT_COMMAND) but it really is a bash configuration like `shopt`.

**Comment by zimbatm** [comment]
Closing as it no longer merges

**Pull request closed without merging**
