### PR TITLE
stdlib: use venv module for python if available

### PR DESCRIPTION
**Pull request by Mic92**
This removes the dependency on virtualenv, because venv is included
in stdlib since python3.3.

### CODE REVIEW

**Comment by Mic92** [comment]
https://docs.python.org/3/library/venv.html

**Comment by Mic92** [comment]
Should I silent this warning?

```
^-- SC2239: Ensure the shebang uses an absolute path to the interpreter.
```

**Comment by Mic92** [comment]
Seems like there is no use for this: https://github.com/direnv/direnv/issues/428

**Comment by Mic92** [comment]
These are the options for `virtualenv`:


```
virtualenv --help
Usage: virtualenv [OPTIONS] DEST_DIR

Options:
  --version             show program's version number and exit
  -h, --help            show this help message and exit
  -v, --verbose         Increase verbosity.
  -q, --quiet           Decrease verbosity.
  -p PYTHON_EXE, --python=PYTHON_EXE
                        The Python interpreter to use, e.g.,
                        --python=python3.5 will use the python3.5 interpreter
                        to create the new environment.  The default is the
                        interpreter that virtualenv was installed with
                        (/nix/store/9vcy8i7mcwmcp486krc22v7851spcdqj-
                        python3-3.7.1/bin/python3.7m)
  --clear               Clear out the non-root install and start from scratch.
  --no-site-packages    DEPRECATED. Retained only for backward compatibility.
                        Not having access to global site-packages is now the
                        default behavior.
  --system-site-packages
                        Give the virtual environment access to the global
                        site-packages.
  --always-copy         Always copy files rather than symlinking.
  --relocatable         Make an EXISTING virtualenv environment relocatable.
                        This fixes up scripts and makes all .pth files
                        relative.
  --no-setuptools       Do not install setuptools in the new virtualenv.
  --no-pip              Do not install pip in the new virtualenv.
  --no-wheel            Do not install wheel in the new virtualenv.
  --extra-search-dir=DIR
                        Directory to look for setuptools/pip distributions in.
                        This option can be used multiple times.
  --download            Download preinstalled packages from PyPI.
  --no-download, --never-download
                        Do not download preinstalled packages from PyPI.
  --prompt=PROMPT       Provides an alternative prompt prefix for this
                        environment.
  --setuptools          DEPRECATED. Retained only for backward compatibility.
                        This option has no effect.
  --distribute          DEPRECATED. Retained only for backward compatibility.
                        This option has no effect.
  --unzip-setuptools    DEPRECATED.  Retained only for backward compatibility.
                        This option has no effect.
```

and this is for `venv`:

```
usage: venv [-h] [--system-site-packages] [--symlinks | --copies] [--clear]
            [--upgrade] [--without-pip]
            ENV_DIR [ENV_DIR ...]

Creates virtual Python environments in one or more target directories.

positional arguments:
  ENV_DIR               A directory to create the environment in.

optional arguments:
  -h, --help            show this help message and exit
  --system-site-packages
                        Give the virtual environment access to the system
                        site-packages dir.
  --symlinks            Try to use symlinks rather than copies, when symlinks
                        are not the default for the platform.
  --copies              Try to use copies rather than symlinks, even when
                        symlinks are the default for the platform.
  --clear               Delete the contents of the environment directory if it
                        already exists, before environment creation.
  --upgrade             Upgrade the environment directory to use this version
                        of Python, assuming Python has been upgraded in-place.
  --without-pip         Skips installing or upgrading pip in the virtual
                        environment (pip is bootstrapped by default)

Once an environment has been created, you may wish to activate it, e.g. by
sourcing an activate script in its bin directory.
```

If you want to go for 100% bug-compatibility this might be a problem if people used `virtualenv` with some options. At the moment it seems that they mostly removed options that were deprecated in virtualenv. The alternative to my implementation would be a new function that you mentioned.

**Comment by eddies** [comment]
@Mic92 If you rebase on master, you can drop your second commit that adds the shellcheck 2239 exception, since that's been merged as part of #432

**Comment by eddies** [comment]
@zimbatm this PR can be closed since it was made part of #505

**Pull request closed without merging**
