### PR TITLE
elvish: replace deprecated `except` with `catch`

### LINKED ISSUE #902: Elvish hook outdated
**Describe the bug**
Elvish hook is outdated. Throws warnings

**To Reproduce**
Install latest version of Elvish as your shell
Install direnv
Hook elvish.

**Expected behavior**
No errors

**Environment**
 - OS: macOS Monterrey
 - Shell: Elvish
 - Direnv version latest

**Additional context**
Replace hook with:

```## hook for direnv
set @edit:before-readline = $@edit:before-readline {
        try {
                var m = [("/usr/local/bin/direnv" export elvish | from-json)]
                if (> (count $m) 0) {
                        set m = (all $m)
                        keys $m | each {|k|
                                if $m[$k] {
                                        set-env $k $m[$k]
                                } else {
                                        unset-env $k
                                }
                        }
                }
        } except e {
                echo $e
        }
}

### PR DESCRIPTION
**Pull request by rsteube**
https://elv.sh/blog/0.18.0-release-notes.html#deprecated-features

fix #902 
related #914

### CODE REVIEW

**Comment by zimbatm** [comment]
thanks!

**Comment by grawlinson** [comment]
This doesn't fix #914.

**Comment by rsteube** [comment]
@grawlinson what's missing?

**Comment by grawlinson** [comment]
The elvish tests in the test directory still contain `except` statements.

**Pull request merged**
