### PR TITLE
Update shell_fish.go to use \X for UTF encoding

### PR DESCRIPTION
**Pull request by nkoch-ops**
This should fix issue #478.

### CODE REVIEW

**Comment by zimbatm** [comment]
I added some tests in https://github.com/direnv/direnv/pull/585 to test UTF-8. If you uncomment the fish test you will see if it fixes it.

**Comment by nkoch-ops** [comment]
Alright, thanks for that.
I already checked manually with a test case that originally caused that error.
The test unfortunately errors out with:
```
Error:
 - expected: ♀♂
 -      got: ♀♂
```
So it looks like the fix seems to work, but the comparison fails for some reason?

**Comment by zimbatm** [comment]
The joys of Unicode. To fix this you will have to see if the hex code of both outputs is the same because Unicode characters can be encoded in multiple ways. In the Go code, you might want to try and iterate over each character instead of bytes by using the `for char := range str {}` iterator instead.

**Comment by zimbatm** [comment]
finally!

**Pull request merged**
